#!/usr/bin/env bash
# TEL Startup file
# these commands are ran only once when a session starts
# this file will be replaced with each update so modifications are not recommended here
termux_color_file=~/.termux/color.properties
temp_color_file=~/.termux/color.temp

source ~/.cache/wal/colors.sh

touch $temp_color_file

echo '# Theme generated by TEL #' >> $temp_color_file
echo background="$background" >> $temp_color_file
echo foreground="$foreground" >> $temp_color_file
echo cursor="$cursor" >> $temp_color_file

echo color0="$color0" >> $temp_color_file
echo color1="$color1" >> $temp_color_file
echo color2="$color2" >> $temp_color_file
echo color3="$color3" >> $temp_color_file
echo color4="$color4" >> $temp_color_file
echo color5="$color5" >> $temp_color_file
echo color6="$color6" >> $temp_color_file
echo color7="$color7" >> $temp_color_file
echo color8="$color8" >> $temp_color_file
echo color9="$color9" >> $temp_color_file
echo color10="$color10" >> $temp_color_file
echo color11="$color11" >> $temp_color_file
echo color12="$color12" >> $temp_color_file
echo color13="$color13" >> $temp_color_file
echo color14="$color14" >> $temp_color_file
echo color15="$color15" >> $temp_color_file

mv -f $termux_color_file ~/.termux/colors.properties.bak
mv -f $temp_color_file $termux_color_file 
exit 0
